// Auto-generated by scripts/generate-news-images.ts.
// Maps article id → public image path. Re-run `npm run gen:news-images`
// to refresh. Empty until images are generated.
export const ARTICLE_IMAGES: Record<string, string> = {
  "ai-design-convergence": "/images/news/ai-design-convergence.png",
  "betting-on-taste": "/images/news/betting-on-taste.png",
  "design-systems": "/images/news/design-systems.png",
  "designing-agents": "/images/news/designing-agents.png",
  "enterprise-ux-debt": "/images/news/enterprise-ux-debt.png",
  "founder-market-fit": "/images/news/founder-market-fit.png",
  "pitch-deck-design": "/images/news/pitch-deck-design.png",
  "studio-notes-q1": "/images/news/studio-notes-q1.png",
};
