// Auto-generated by scripts/generate-news-images.ts.
// Maps article id → public image path. Empty until images are generated.
// Run `npm run gen:news-images` after adding your RECRAFT_API_KEY to .env.local.
export const ARTICLE_IMAGES: Record<string, string> = {};
