/**
 * Proposal microsites — generated by the Proposal Engine skill chain.
 *
 * ⚠️ THIS REPO IS PUBLIC. Do not commit real client proposals here. Proposals
 * hold client context and pricing. Use this only for demo/sample proposals; for
 * a real client, render the standalone HTML from the brain, or move proposal
 * storage to a private store (env/DB/KV) before sending. Every route is
 * `noindex`, but noindex is not privacy — a public repo is still public.
 *
 * Mirrors the data-module pattern in lib/projects.ts.
 */

export type ProposalPlanStep = {
  step: "Clarify" | "Design the system" | "Build the MVP" | "Ship & iterate";
  summary: string;
  weeks: string;
};

export type Proposal = {
  slug: string;
  client: { name: string; sector: string; contact: string };
  /** Problem-led, not us-led. */
  hero: { headline: string; subline: string };
  problem: {
    problem: string;
    user: string;
    need: string;
    successMetric: string;
    aiLeverage: string;
  };
  /** Exactly 4 steps, in order. */
  plan: ProposalPlanStep[];
  timeline: string;
  /** One number/range, or "[NEEDS JOHN]" until pricing is confirmed. */
  investment: { amount: string; note: string };
  /** One sector-matched case study. */
  proof: { project: string; sector: string; outcome: string };
  cta: { label: string; href: string };
};

export const proposals: Proposal[] = [
  {
    slug: "northwind",
    client: {
      name: "Northwind",
      sector: "Fintech",
      contact: "Mara Lindqvist, founder/CEO",
    },
    hero: {
      headline: "Saving from an irregular income shouldn't take willpower.",
      subline:
        "Let's prove the AI copilot is buildable and fundable in six weeks.",
    },
    problem: {
      problem:
        "You have a sharp idea but no way yet to show it's buildable or fundable, and a worry that it's too complex to explain.",
      user: "Gig workers with irregular income who struggle to save consistently.",
      need: "Make 'save automatically from uneven income' feel obvious.",
      successMetric:
        "An investor-ready MVP a contractor can build without translation, in ~6 weeks.",
      aiLeverage:
        "A copilot that reads income patterns and nudges the right amount at the right time — the product, not a bolt-on feature.",
    },
    plan: [
      {
        step: "Clarify",
        summary:
          "Align on the one job worth proving for investors, the gig worker we design for, and the single success metric. Decide where the AI copilot earns its place.",
        weeks: "Week 1",
      },
      {
        step: "Design the system",
        summary:
          "Design the copilot's logic first — how it reads income, decides a nudge, and behaves when unsure — before any screens.",
        weeks: "Weeks 2–3",
      },
      {
        step: "Build the MVP",
        summary:
          "Rapid, MVP-ready design your contractor can build without translation. Every state defined: empty, loading, nudge, success.",
        weeks: "Weeks 4–5",
      },
      {
        step: "Ship & iterate",
        summary:
          "Instrument it to watch real behaviour, then prepare the story and screens for your investor conversations.",
        weeks: "Week 6",
      },
    ],
    timeline: "6 weeks",
    investment: {
      amount: "From £12,000",
      note: "Fixed for the sprint scope — no agency padding, no hidden extras. (Placeholder pricing; confirm before sending.)",
    },
    proof: {
      project: "Rinkl",
      sector: "Fintech",
      outcome:
        "A next-gen student finance tracker with real-time insights and AI-powered nudges for better financial health. Same core challenge as yours: turning messy, irregular money into a product that feels effortless and trustworthy.",
    },
    cta: {
      label: "Start a project",
      href: "mailto:hello@rulz.co?subject=Northwind%20%C3%97%20Rulz%26Co",
    },
  },
];

export function getProposal(slug: string): Proposal | undefined {
  return proposals.find((p) => p.slug === slug);
}
